name: Lint with Prettier

on: [push, fork]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install prettier
        run: yarn add prettier
      - name: Run prettier
        run: yarn prettier --config prettierrc.json  --check "{components, pages}/**/*.{js,jsx,ts,tsx}"
